A3:		main.o Control.o School.o CourseArray.o StuArray.o RegList.o Course.o Student.o Registration.o View.o
	g++ -o a3 main.o Control.o School.o CourseArray.o StuArray.o RegList.o Course.o Student.o Registration.o View.o

main.o: main.cc
	g++ -c main.cc

Control.o: Control.cc
	g++ -c Control.cc

School.o: School.cc
	g++ -c School.cc

CourseArray.o: CourseArray.cc
	g++ -c CourseArray.cc

StuArray.o: StuArray.cc
	g++ -c StuArray.cc

RegList.o: RegList.cc
	g++ -c RegList.cc

Course.o: Course.cc
	g++ -c Course.cc

Student.o: Student.cc
	g++ -c Student.cc

Registration.o: Registration.cc
	g++ -c Registration.cc

View.o: View.cc
	g++ -c View.cc
	
clean: 
	rm -f *.o a3
