A4:		main.o random.o Position.o Pit.o Participant.o PartArray.o Hero.o Snorc.o Escape.o 
	g++ -o a4 main.o random.o Position.o Pit.o Participant.o PartArray.o Hero.o Snorc.o Escape.o

main.o: main.cc
	g++ -c main.cc

random.o: random.cc
	g++ -c random.cc

Position.o: Position.cc
	g++ -c Position.cc

Pit.o: Pit.cc
	g++ -c Pit.cc

Participant.o: Participant.cc
	g++ -c Participant.cc

PartArray.o: PartArray.cc
	g++ -c PartArray.cc

Hero.o: Hero.cc
	g++ -c Hero.cc

Snorc.o: Snorc.cc
	g++ -c Snorc.cc

Escape.o: Escape.cc
	g++ -c Escape.cc

clean: 
	rm -f *.o a4
