A5:		main.o random.o Participant.o Hero.o Snorc.o Ninja.o Escape.o EscapeeBehaviour.o RescuedBehaviour.o RescuerBehaviour.o VillainBehaviour.o MoveBehaviour.o
	g++ -g -o a5 main.o random.o Participant.o Hero.o Snorc.o Ninja.o Escape.o EscapeeBehaviour.o RescuedBehaviour.o RescuerBehaviour.o VillainBehaviour.o MoveBehaviour.o

main.o: main.cc
	g++ -g -c main.cc

random.o: random.cc
	g++ -g -c random.cc

Participant.o: Participant.cc
	g++ -g -c Participant.cc

Hero.o: Hero.cc
	g++ -g -c Hero.cc

Snorc.o: Snorc.cc
	g++ -g -c Snorc.cc

Ninja.o: Ninja.cc
	g++ -g -c Ninja.cc	

Escape.o: Escape.cc
	g++ -g -c Escape.cc

EscapeeBehaviour.o: EscapeeBehaviour.cc
	g++ -g -c EscapeeBehaviour.cc

RescuedBehaviour.o: RescuedBehaviour.cc
	g++ -g -c RescuedBehaviour.cc

RescuerBehaviour.o: RescuerBehaviour.cc
	g++ -g -c RescuerBehaviour.cc

VillainBehaviour.o: VillainBehaviour.cc
	g++ -g -c VillainBehaviour.cc

MoveBehaviour.o: MoveBehaviour.cc
	g++ -g -c MoveBehaviour.cc

clean: 
	rm -f *.o a5
